name: Test CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "docs/**"
      - "playground/**"
      - "*.md"
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"

      - name: Cache core files
        uses: actions/cache@v4
        id: cache-core
        with:
          path: |
            core/*
            !core/live2d.d.ts
          key: ${{ hashFiles('scripts/setup.js') }}

      - run: npm ci
      - run: npm install @rollup/rollup-linux-x64-gnu --force

      - name: Set up core files
        if: steps.cache-core.outputs.cache-hit != 'true'
        run: |
          echo Cache miss: ${{ hashFiles('scripts/setup.js') }}
          npm run setup

      - run: npm run type
      - run: npm run build


      - name: Commit files
        run: |
          git config --global user.name 'RaSan147'
          git config --global user.email '34002411+RaSan147@users.noreply.github.com'

          # Check if there are changes
          if ! git diff --quiet; then
            git add --all
            git commit -m "Automated report"
            git push
          else
            echo "No changes to commit."
          fi


      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/dist

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: diff-images
          path: test/**/__image_snapshots__/__diff_output__/*
          if-no-files-found: ignore
          
